pip install --upgrade pip
pip3 install Pillow
pip3 install PyGithub
pip3 install moviepy
pip3 install aiofiles
pip3 install vcam
pip3 install pokedex.py
pip3 install backports.lzma
pip3 install spotdl
pip3 install aiohttp
pip3 install pygments
pip3 install appdirs
pip3 install async_generator
pip3 install beautifulsoup4
pip3 install bs4
pip3 install bwb
pip3 install cfscrape
pip3 install coffeehouse
pip3 install cowpy
pip3 install cryptg
pip3 install dnspython
pip3 install emoji
pip3 install faker
pip3 install gTTS-token
pip3 install gTTS
pip3 install gitpython
pip3 install glitch_this
pip3 install google-api-python-client
pip3 install google-auth-oauthlib
pip3 install google_images_download
pip3 install googletrans
pip3 install google
pip3 install geopy
pip3 install gsearch
pip3 install hachoir
pip3 install heroku3
pip3 install httplib2
pip3 install humanize
pip3 install justwatch
pip3 install keyboard
pip3 install lottie
pip3 install lyrics_extractor
pip3 install lxml
pip3 install oauth2client
pip3 install opencv-python-headless
pip3 install patool
pip3 install psutil
pip3 install psycopg2-binary
pip3 install pygame
pip3 install PyLyrics
pip3 install pySmartDL
pip3 install pybase64
pip3 install pyfiglet
pip3 install pylast
pip3 install pymongo
pip3 install python-barcode
pip3 install python-dotenv
pip3 install python-magic
pip3 install pytube
pip3 install pytz
pip3 install qrcode
pip3 install regex
pip3 install requests
pip3 install scipy
pip3 install scapy
pip3 install search-engine-parser
pip3 install selenium
pip3 install speedtest-cli
pip3 install spotify_token
pip3 install sqlalchemy
pip3 install telegraph
pip3 install urbandict
pip3 install validators
pip3 install wikipedia
pip3 install youtube_dl
pip3 install youtube_search
pip3 install youtube-search-python
pip3 install covid
pip3 install tswift
pip3 install telethon
